### PR TITLE
v3.18 FOSS

### PR DESCRIPTION
**Pull request by thermatk**
- v3.18 merged in multiple commits, a big part should be reviewed (see [REVIEW]), yet a lot of code and binaries are tagged [safe]

- Telegram-FOSS patches applied from scratch, except for JNI, Giphy(not harming privacy in any way) and some old leftovers.

- ToDo JNI: this part is back to upstream state for now, so work replacing prebuilts and allowing x86 should be redone. For now, it compiles for armv7 just as good as upstream does

### CODE REVIEW

**Comment by Bubu** [comment]
@thermatk Gah, I'm still fighting with gradle Android studio. 
How do you configure the signing configs without patching the `TMessageProj/build.gradle` file with the correct info for my setup?

**Comment by Bubu** [comment]
@thermatk I'll start applying the changes one by one tomorrow. I'd like to keep the authorship of the changes though (DrKlo, slp, etc...) I can do this locally with git.

One question though:  What's the point of the first commit `Update to 3.18.0`? I thought this one is actually split into all the smaller later ones.

**Comment by thermatk** [comment]
@Bubu in this case the first commit just played it's role for the gitmodule to be recognized by github, it somehow didn't see it otherwise.
Why I couldn't maintain DrKLO's commit is evident, but I don't even know how you'll actually cherry pick all the random commits from this repo. Some of them are seriously outdated or contain too many mixed changes. Maybe you're way cooler in git-magic :)
Multiple changelists in Studio are the way to go with config files for me

**Comment by thermatk** [comment]
i actually made this 1by1 commits for easier review anyway :)

**Comment by thermatk** [comment]
@Bubu I think I do. It's used for the verification method when Telegram calls you, without these permissions it can't cancel a call(LoginActivity.java):
`                   
 if (!allowCancelCall) {
                        permissionsItems.add(Manifest.permission.CALL_PHONE);
                        permissionsItems.add(Manifest.permission.WRITE_CALL_LOG);
                        permissionsItems.add(Manifest.permission.READ_CALL_LOG);
}
`
those are used afterwards in AndroidUtilities.java for endIncomingCall() and removeLoginPhoneCall()

**Pull request closed without merging**
