### PR TITLE
[WiP] Inital emojiOne support.

### PR DESCRIPTION
**Pull request by Bubu**
There is a new python script in Tools/ which scrapes emojipedia.org to
sort the emojiOne emojis into their categories.
It then reads their offset in the provided spritesheet from some .css
file and generates a new EmojiData.java file from that.

Still needed:
- Implement the option to allow switching emojis.
- ~~Give attribution to emojiOne somewhere in Settings~~ done
- Test everything with different screen sizes/resolutions/dpi, it is quite probably broken somewhere...
- Maybe: Speed up emoji loading with native code?

ref. #35

### CODE REVIEW

**Comment by Ecron** [comment]
I gladly help you with the testing, and anything else that doesn't require deep coding skills/knowledge. Maybe you can give credit under the Telegram version, down in the Settings screen. Something like "emoji set thanks to emojione.com" under "Telegram for Android vX.X.X (XXX)".

**Comment by slp** [comment]
@Bubu Do you feel this is ready for inclusion in 3.3.2?

**Comment by Bubu** [comment]
The option to switch emojis is not done yet. I have some work done there on my PC. I'll see if I can finish that in the next few days. 
Then we'd need to do some testing with different device sizes and specs.

**Comment by Ecron** [comment]
Again, I offer my help for testing purposes. I own a 3,5" Samsung device, Android 2.3.7, and a 4,0" LG one, Android 4.1.2.

**Comment by Bubu** [comment]
I forgot I need to adapt my code to the new upstream version...

I'll see if I can get around to this. But probably not for 3.3.2.

**Comment by Peque** [comment]
@Bubu any updates on this matter?

**Comment by Peque** [comment]
@Bubu any updates on this matter? :blush:

**Comment by slp** [comment]
@Bubu Having replaced the conflicting assets with FOSS friendly sprite sheets, do you think this is still needed?

**Comment by Bubu** [comment]
This code is quite obsolete anyway, so it can be closed.
I actually prefer having the native android emojis, but I don't think I will get around to implementing the toggle option.

**Pull request closed without merging**
