### PR TITLE
Add location sharing from OSMAnd.

### PR DESCRIPTION
**Pull request by Bubu**
This is not an optimal solution yet but it should work reasonably well together with OSMAnd.
I'll post further thoughts to the issue #27.

### CODE REVIEW

**Comment by jomo** [comment]
:+1: although this raises a few questions:

0. Is this really specific to OsmAnd, or can it handle `geo:` intents in general?
0. Do other (google-) maps use different intents?
0. Wouldn't it be better to pull this in at [DrKLO/Telegram](https://github.com/DrKLO/Telegram)?

**Comment by Bubu** [comment]
I wrote something about this in [#27](https://github.com/slp/Telegram-FOSS/issues/27#issuecomment-145037138).

1. This is not the `ACTION_VIEW` intent with `geo:` data specified [here](https://developer.android.com/guide/components/intents-common.html#Maps) because we don't want to view a map. It is an `ACTION_SEND` which encodes the same `geo` URI. And this might be specific to OsmAnd. (?)
2. What other maps applications besides google maps are there? I know about [Locus Map](http://www.locusmap.eu/) and [Orux Maps](http://www.oruxmaps.com/). But I haven't gotten around to testing yet.
3. Definitely. And I probably will submit it, when it's done. But I don't have high hopes that it will be ever be merged or even be looked at.

**Comment by Bubu** [comment]
I tested:
 - Google maps: Just shares a google maps short url. Not useful.
 - Orux Maps: Shares a location via ```geo:Lat,Long,zoom\nhttp://maps.google.com/maps?q=Lat,Long```
 - Locus Map: Free form text, defaults to" ```<adress>, Lat, Lon``` But these coordinates are in one of 3 user selectable formats

Could not test (no x86 libraries included and arm emulator is very slow):
 - HERE maps 
 - Waze maps

**Comment by slp** [comment]
@Bubu Same question, is this ready to be included in 3.3.2 (when upstream releases the code)?

**Comment by Bubu** [comment]
Yes, I think I can wrap this up in the next few days.

**Comment by Bubu** [comment]
This should be safe to include in the next build. I'll push it to the merge 3.3.2 branch.
It doesn't include a way to share a location from telegram. Just from OSMAnd and Orux to Telegram.
But it does show a 'Not implemented' warning when truing to attach a location object.

**Comment by Bubu** [comment]
Sorry about the messy history. I can create a clean PR/patch if you want to but I don't have much time now.

**Pull request closed without merging**
